services:
  - type: web
    name: election-analytics-platform
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MONGO_URI
        sync: false # You must set this manually in the Render dashboard
